CREATE TABLE woorisai.participant
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slot         SMALLINT                   NOT NULL,
    display_name VARCHAR(30)                NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE   NOT NULL,
    CONSTRAINT participant_pk PRIMARY KEY (id),
    CONSTRAINT participant_slot_uq UNIQUE (slot),
    CONSTRAINT participant_display_name_uq UNIQUE (display_name),
    CONSTRAINT participant_slot_ck CHECK (slot = 1 OR slot = 2),
    CONSTRAINT participant_display_name_ck CHECK (char_length(trim(display_name)) > 0)
);

CREATE TABLE woorisai.participant_credential
(
    participant_id BIGINT                   NOT NULL,
    pin_hash       VARCHAR(255)             NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT participant_credential_pk PRIMARY KEY (participant_id),
    CONSTRAINT participant_credential_participant_fk
        FOREIGN KEY (participant_id) REFERENCES woorisai.participant (id) ON DELETE RESTRICT,
    CONSTRAINT participant_credential_pin_hash_ck CHECK (char_length(trim(pin_hash)) > 0)
);

CREATE TABLE woorisai.relationship_score
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_participant_id BIGINT                   NOT NULL,
    target_participant_id BIGINT                   NOT NULL,
    current_score         SMALLINT                 NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT relationship_score_pk PRIMARY KEY (id),
    CONSTRAINT relationship_score_source_uq UNIQUE (source_participant_id),
    CONSTRAINT relationship_score_target_uq UNIQUE (target_participant_id),
    CONSTRAINT relationship_score_id_source_uq UNIQUE (id, source_participant_id),
    CONSTRAINT relationship_score_source_fk
        FOREIGN KEY (source_participant_id) REFERENCES woorisai.participant (id) ON DELETE RESTRICT,
    CONSTRAINT relationship_score_target_fk
        FOREIGN KEY (target_participant_id) REFERENCES woorisai.participant (id) ON DELETE RESTRICT,
    CONSTRAINT relationship_score_participants_ck
        CHECK (source_participant_id <> target_participant_id),
    CONSTRAINT relationship_score_value_ck CHECK (current_score BETWEEN 0 AND 100)
);

CREATE TABLE woorisai.score_change
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    relationship_score_id BIGINT                   NOT NULL,
    changed_by_id         BIGINT                   NOT NULL,
    delta                 SMALLINT                 NOT NULL,
    resulting_score       SMALLINT                 NOT NULL,
    reason                VARCHAR(200),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT score_change_pk PRIMARY KEY (id),
    CONSTRAINT score_change_outgoing_owner_fk
        FOREIGN KEY (relationship_score_id, changed_by_id)
            REFERENCES woorisai.relationship_score (id, source_participant_id) ON DELETE RESTRICT,
    CONSTRAINT score_change_delta_ck CHECK (delta BETWEEN -100 AND 100 AND delta <> 0),
    CONSTRAINT score_change_result_ck CHECK (resulting_score BETWEEN 0 AND 100),
    CONSTRAINT score_change_reason_ck CHECK (reason IS NULL OR char_length(trim(reason)) > 0)
);

CREATE INDEX score_change_history_idx
    ON woorisai.score_change (relationship_score_id, created_at DESC, id DESC);

CREATE TABLE woorisai.score_change_comment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    score_change_id BIGINT                   NOT NULL,
    author_id       BIGINT                   NOT NULL,
    content         VARCHAR(500),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT score_change_comment_pk PRIMARY KEY (id),
    CONSTRAINT score_change_comment_change_fk
        FOREIGN KEY (score_change_id) REFERENCES woorisai.score_change (id) ON DELETE RESTRICT,
    CONSTRAINT score_change_comment_author_fk
        FOREIGN KEY (author_id) REFERENCES woorisai.participant (id) ON DELETE RESTRICT,
    CONSTRAINT score_change_comment_content_ck
        CHECK (content IS NULL OR char_length(trim(content)) > 0)
);

CREATE INDEX score_change_comment_thread_idx
    ON woorisai.score_change_comment (score_change_id, created_at, id);

CREATE TABLE woorisai.diary_entry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id  BIGINT                   NOT NULL,
    content    VARCHAR(1000)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT diary_entry_pk PRIMARY KEY (id),
    CONSTRAINT diary_entry_author_fk
        FOREIGN KEY (author_id) REFERENCES woorisai.participant (id) ON DELETE RESTRICT,
    CONSTRAINT diary_entry_content_ck CHECK (char_length(trim(content)) > 0),
    CONSTRAINT diary_entry_timestamps_ck CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE INDEX diary_entry_list_idx ON woorisai.diary_entry (created_at DESC, id DESC);

CREATE TABLE woorisai.diary_entry_comment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    diary_entry_id BIGINT                   NOT NULL,
    author_id      BIGINT                   NOT NULL,
    content        VARCHAR(500)             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT diary_entry_comment_pk PRIMARY KEY (id),
    CONSTRAINT diary_entry_comment_entry_fk
        FOREIGN KEY (diary_entry_id) REFERENCES woorisai.diary_entry (id) ON DELETE CASCADE,
    CONSTRAINT diary_entry_comment_author_fk
        FOREIGN KEY (author_id) REFERENCES woorisai.participant (id) ON DELETE RESTRICT,
    CONSTRAINT diary_entry_comment_content_ck CHECK (char_length(trim(content)) > 0),
    CONSTRAINT diary_entry_comment_timestamps_ck CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE INDEX diary_entry_comment_thread_idx
    ON woorisai.diary_entry_comment (diary_entry_id, created_at, id);

CREATE TABLE woorisai.media_attachment
(
    id                      UUID                     NOT NULL,
    uploader_id             BIGINT                   NOT NULL,
    score_change_id         BIGINT,
    score_change_comment_id BIGINT,
    diary_entry_id          BIGINT,
    purpose                 VARCHAR(24)              NOT NULL,
    kind                    VARCHAR(8)               NOT NULL,
    status                  VARCHAR(8)               NOT NULL,
    object_key              VARCHAR(255)             NOT NULL,
    original_name           VARCHAR(255)             NOT NULL,
    content_type            VARCHAR(100)             NOT NULL,
    expected_size           BIGINT                   NOT NULL,
    actual_size             BIGINT,
    position                SMALLINT                 NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    ready_at                TIMESTAMP WITH TIME ZONE,
    CONSTRAINT media_attachment_pk PRIMARY KEY (id),
    CONSTRAINT media_attachment_object_key_uq UNIQUE (object_key),
    CONSTRAINT media_attachment_object_key_ck CHECK (char_length(trim(object_key)) > 0),
    CONSTRAINT media_attachment_uploader_fk
        FOREIGN KEY (uploader_id) REFERENCES woorisai.participant (id) ON DELETE RESTRICT,
    CONSTRAINT media_attachment_score_change_fk
        FOREIGN KEY (score_change_id) REFERENCES woorisai.score_change (id) ON DELETE RESTRICT,
    CONSTRAINT media_attachment_score_comment_fk
        FOREIGN KEY (score_change_comment_id)
            REFERENCES woorisai.score_change_comment (id) ON DELETE RESTRICT,
    CONSTRAINT media_attachment_diary_entry_fk
        FOREIGN KEY (diary_entry_id) REFERENCES woorisai.diary_entry (id) ON DELETE CASCADE,
    CONSTRAINT media_attachment_purpose_ck CHECK (
        purpose = 'SCORE_CHANGE'
        OR purpose = 'SCORE_CHANGE_COMMENT'
        OR purpose = 'DIARY_ENTRY'
    ),
    CONSTRAINT media_attachment_kind_ck CHECK (kind = 'IMAGE' OR kind = 'VIDEO'),
    CONSTRAINT media_attachment_status_ck CHECK (status = 'PENDING' OR status = 'READY'),
    CONSTRAINT media_attachment_score_kind_ck CHECK (purpose <> 'SCORE_CHANGE' OR kind = 'IMAGE'),
    CONSTRAINT media_attachment_name_ck CHECK (char_length(trim(original_name)) > 0),
    CONSTRAINT media_attachment_content_type_ck CHECK (char_length(trim(content_type)) > 0),
    CONSTRAINT media_attachment_position_ck CHECK (position >= 0),
    CONSTRAINT media_attachment_score_position_ck
        CHECK (purpose <> 'SCORE_CHANGE' OR position = 0),
    CONSTRAINT media_attachment_expected_size_ck CHECK (
        expected_size > 0
        AND expected_size <= CASE kind WHEN 'IMAGE' THEN 10485760 ELSE 104857600 END
    ),
    CONSTRAINT media_attachment_actual_size_ck CHECK (
        actual_size IS NULL
        OR (
            actual_size > 0
            AND actual_size <= CASE kind WHEN 'IMAGE' THEN 10485760 ELSE 104857600 END
        )
    ),
    CONSTRAINT media_attachment_state_ck CHECK (
        (
            status = 'PENDING'
            AND position = 0
            AND actual_size IS NULL
            AND ready_at IS NULL
            AND score_change_id IS NULL
            AND score_change_comment_id IS NULL
            AND diary_entry_id IS NULL
        )
        OR
        (
            status = 'READY'
            AND actual_size IS NOT NULL
            AND actual_size = expected_size
            AND ready_at IS NOT NULL
            AND ready_at >= created_at
            AND (
                (
                    score_change_id IS NULL
                    AND score_change_comment_id IS NULL
                    AND diary_entry_id IS NULL
                    AND position = 0
                )
                OR (
                    purpose = 'SCORE_CHANGE'
                    AND score_change_id IS NOT NULL
                    AND score_change_comment_id IS NULL
                    AND diary_entry_id IS NULL
                )
                OR (
                    purpose = 'SCORE_CHANGE_COMMENT'
                    AND score_change_id IS NULL
                    AND score_change_comment_id IS NOT NULL
                    AND diary_entry_id IS NULL
                )
                OR (
                    purpose = 'DIARY_ENTRY'
                    AND score_change_id IS NULL
                    AND score_change_comment_id IS NULL
                    AND diary_entry_id IS NOT NULL
                )
            )
        )
    )
);

CREATE UNIQUE INDEX media_attachment_score_uq
    ON woorisai.media_attachment (score_change_id);
CREATE UNIQUE INDEX media_attachment_score_comment_position_uq
    ON woorisai.media_attachment (score_change_comment_id, position);
CREATE UNIQUE INDEX media_attachment_diary_position_uq
    ON woorisai.media_attachment (diary_entry_id, position);
CREATE INDEX media_attachment_uploader_status_idx
    ON woorisai.media_attachment (uploader_id, status, created_at, id);

CREATE TABLE woorisai.notification_fid
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    participant_id BIGINT                   NOT NULL,
    fid            VARCHAR(255)             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT notification_fid_pk PRIMARY KEY (id),
    CONSTRAINT notification_fid_value_uq UNIQUE (fid),
    CONSTRAINT notification_fid_participant_fk
        FOREIGN KEY (participant_id) REFERENCES woorisai.participant (id) ON DELETE RESTRICT,
    CONSTRAINT notification_fid_value_ck
        CHECK (REGEXP_LIKE(fid, '^[A-Za-z0-9_-]{22}$'))
);

CREATE INDEX notification_fid_participant_idx
    ON woorisai.notification_fid (participant_id, id);

CREATE TABLE woorisai.event_publication
(
    id                     UUID                        NOT NULL,
    completion_date        TIMESTAMP(9) WITH TIME ZONE,
    event_type             VARCHAR(512)                NOT NULL,
    listener_id            VARCHAR(512)                NOT NULL,
    publication_date       TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    serialized_event       VARCHAR(4000)               NOT NULL,
    status                 VARCHAR(20),
    completion_attempts    INT,
    last_resubmission_date TIMESTAMP(9) WITH TIME ZONE,
    CONSTRAINT event_publication_pk PRIMARY KEY (id)
);

CREATE INDEX event_publication_by_listener_and_serialized_event_idx
    ON woorisai.event_publication (listener_id, serialized_event);
CREATE INDEX event_publication_by_completion_date_idx
    ON woorisai.event_publication (completion_date);
